# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{noah}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["lusis"]
  s.date = %q{2011-02-07}
  s.default_executable = %q{noah}
  s.description = %q{Lightweight registry based on Apache Zookeeper}
  s.email = %q{lusis.org+rubygems.org@gmail.com}
  s.executables = ["noah"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".autotest",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "autotest/discover.rb",
    "bin/noah",
    "config.ru",
    "doc/coverage/index.html",
    "doc/coverage/jquery-1.3.2.min.js",
    "doc/coverage/jquery.tablesorter.min.js",
    "doc/coverage/lib-helpers_rb.html",
    "doc/coverage/lib-models_rb.html",
    "doc/coverage/noah_rb.html",
    "doc/coverage/print.css",
    "doc/coverage/rcov.js",
    "doc/coverage/screen.css",
    "lib/noah.rb",
    "lib/noah/app.rb",
    "lib/noah/applications.rb",
    "lib/noah/configurations.rb",
    "lib/noah/helpers.rb",
    "lib/noah/hosts.rb",
    "lib/noah/models.rb",
    "lib/noah/services.rb",
    "lib/noah/watchers.rb",
    "spec/application_spec.rb",
    "spec/configuration_spec.rb",
    "spec/host_spec.rb",
    "spec/noahapp_application_spec.rb",
    "spec/noahapp_configuration_spec.rb",
    "spec/noahapp_host_spec.rb",
    "spec/noahapp_service_spec.rb",
    "spec/noahapp_spec.rb",
    "spec/service_spec.rb",
    "spec/spec_helper.rb",
    "views/200.erb",
    "views/404.erb",
    "views/500.erb",
    "views/index.haml"
  ]
  s.homepage = %q{http://github.com/lusis/noah}
  s.licenses = ["Apache 2.0"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Lightweight registry based on Apache Zookeeper}
  s.test_files = [
    "spec/application_spec.rb",
    "spec/configuration_spec.rb",
    "spec/host_spec.rb",
    "spec/noahapp_application_spec.rb",
    "spec/noahapp_configuration_spec.rb",
    "spec/noahapp_host_spec.rb",
    "spec/noahapp_service_spec.rb",
    "spec/noahapp_spec.rb",
    "spec/service_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, ["= 1.1.2"])
      s.add_runtime_dependency(%q<sinatra-namespace>, ["= 0.6.1"])
      s.add_runtime_dependency(%q<ohm>, ["= 0.1.3"])
      s.add_runtime_dependency(%q<ohm-contrib>, ["= 0.1.0"])
      s.add_runtime_dependency(%q<haml>, ["= 3.0.25"])
      s.add_runtime_dependency(%q<rake>, ["= 0.8.7"])
      s.add_runtime_dependency(%q<vegas>, ["= 0.1.8"])
      s.add_runtime_dependency(%q<yajl-ruby>, ["= 0.7.9"])
      s.add_runtime_dependency(%q<json-jruby>, ["= 1.4.6"])
      s.add_runtime_dependency(%q<warbler>, ["= 1.2.1"])
      s.add_runtime_dependency(%q<jruby-openssl>, ["= 0.7.3"])
      s.add_runtime_dependency(%q<rack-jetty>, ["= 0.2.0"])
      s.add_development_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_development_dependency(%q<sinatra-reloader>, ["= 0.5.0"])
      s.add_development_dependency(%q<rspec>, ["= 2.4.0"])
      s.add_development_dependency(%q<rcov>, ["= 0.9.9"])
      s.add_development_dependency(%q<rack-test>, ["= 0.5.7"])
      s.add_development_dependency(%q<ZenTest>, ["= 4.4.2"])
      s.add_development_dependency(%q<autotest>, ["= 4.4.6"])
      s.add_development_dependency(%q<autotest-growl>, ["= 0.2.9"])
    else
      s.add_dependency(%q<sinatra>, ["= 1.1.2"])
      s.add_dependency(%q<sinatra-namespace>, ["= 0.6.1"])
      s.add_dependency(%q<ohm>, ["= 0.1.3"])
      s.add_dependency(%q<ohm-contrib>, ["= 0.1.0"])
      s.add_dependency(%q<haml>, ["= 3.0.25"])
      s.add_dependency(%q<rake>, ["= 0.8.7"])
      s.add_dependency(%q<vegas>, ["= 0.1.8"])
      s.add_dependency(%q<yajl-ruby>, ["= 0.7.9"])
      s.add_dependency(%q<json-jruby>, ["= 1.4.6"])
      s.add_dependency(%q<warbler>, ["= 1.2.1"])
      s.add_dependency(%q<jruby-openssl>, ["= 0.7.3"])
      s.add_dependency(%q<rack-jetty>, ["= 0.2.0"])
      s.add_dependency(%q<jeweler>, ["= 1.5.2"])
      s.add_dependency(%q<sinatra-reloader>, ["= 0.5.0"])
      s.add_dependency(%q<rspec>, ["= 2.4.0"])
      s.add_dependency(%q<rcov>, ["= 0.9.9"])
      s.add_dependency(%q<rack-test>, ["= 0.5.7"])
      s.add_dependency(%q<ZenTest>, ["= 4.4.2"])
      s.add_dependency(%q<autotest>, ["= 4.4.6"])
      s.add_dependency(%q<autotest-growl>, ["= 0.2.9"])
    end
  else
    s.add_dependency(%q<sinatra>, ["= 1.1.2"])
    s.add_dependency(%q<sinatra-namespace>, ["= 0.6.1"])
    s.add_dependency(%q<ohm>, ["= 0.1.3"])
    s.add_dependency(%q<ohm-contrib>, ["= 0.1.0"])
    s.add_dependency(%q<haml>, ["= 3.0.25"])
    s.add_dependency(%q<rake>, ["= 0.8.7"])
    s.add_dependency(%q<vegas>, ["= 0.1.8"])
    s.add_dependency(%q<yajl-ruby>, ["= 0.7.9"])
    s.add_dependency(%q<json-jruby>, ["= 1.4.6"])
    s.add_dependency(%q<warbler>, ["= 1.2.1"])
    s.add_dependency(%q<jruby-openssl>, ["= 0.7.3"])
    s.add_dependency(%q<rack-jetty>, ["= 0.2.0"])
    s.add_dependency(%q<jeweler>, ["= 1.5.2"])
    s.add_dependency(%q<sinatra-reloader>, ["= 0.5.0"])
    s.add_dependency(%q<rspec>, ["= 2.4.0"])
    s.add_dependency(%q<rcov>, ["= 0.9.9"])
    s.add_dependency(%q<rack-test>, ["= 0.5.7"])
    s.add_dependency(%q<ZenTest>, ["= 4.4.2"])
    s.add_dependency(%q<autotest>, ["= 4.4.6"])
    s.add_dependency(%q<autotest-growl>, ["= 0.2.9"])
  end
end

